apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-go-rhtap-three-component-scenarios-b17s
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-go-rhtap-three-component-scenarios-b17s
    app.kubernetes.io/part-of: mc-three-scenarios
  name: devfile-go-rhtap-three-component-scenarios-b17s
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-go-rhtap-three-component-scenarios-b17s
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-go-rhtap-three-component-scenarios-b17s
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-msfr-tenant/mc-three-scenarios/devfile-go-rhtap-three-component-scenarios-b17s@sha256:6c01ddd7aaef6c8d6d1a3b97226434f3040ce29d172a92a7010930701fb5b6ff
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
